databases:
  - name: signals-db
    plan: basic-256mb
    databaseName: signals
    user: signals

services:
  - type: web
    name: signals
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    preDeployCommand: "DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:prepare db:schema:load:queue db:schema:load:cache"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: signals-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
